version: "3.8"
services:
  server:
    build:
      dockerfile: ./Dockerfile
    image: psyb0t/telegram-logger:local
    ports:
      - 8080:80
    volumes:
      - ./config.yml:/app/config.yml
      - ./db:/app/db
    environment:
      - CONFIGFILE=/app/config.yml
      - TELEGRAMBOT_TOKEN=${TELEGRAMBOT_TOKEN}
      # if storage type is badgerDB (currently the only supported one)
      - STORAGE_BADGERDB_DSN=/app/db
