version: "3.8"
services:
  server:
    build:
      dockerfile: ./Dockerfile
    image: github.com/psyb0t/telegram-logger
    ports:
      - 8080:80
    volumes:
      - ./config.yml:/root/config.yml
    environment:
      - CONFIGFILE=/root/config.yml
